### PR TITLE
Adding mapper 003

### PR DESCRIPTION
**Pull request by Ricardicus**
I have added a mapper for CNROM, the INES Mapper 003!

https://www.nesdev.org/wiki/INES_Mapper_003

These games might use a different pallette than 2C02, 
so the rendering might not look so good. But that
can be improved upon in the future.

### CODE REVIEW

**Comment by Ricardicus** [comment]
References:

https://www.nesdev.org/wiki/CNROM 
https://www.nesdev.org/wiki/INES_Mapper_003

**Comment by Ricardicus** [comment]
tested on titles:
Cybernoid - The Fighting Machine,
VS Super Mario Bros (VS)
Arkanoid (U)

All these programs have 32 KB PRG ROM,
not tested on any mirrored 16 KB PRG ROM.

**Review by johnor — APPROVED** [review]
Great! Thanks for the PR!

**Comment by johnor** [comment]
The coverage job failed due to some missing test cover:
core/src/rom/mapper_3.cpp                     64      33    51%   20,25,39,43,63-65,73-75,79,93-94,96-97,99-100,102-103,105-106,108,110-111,113-114,116-117,119-120,123
Can you add some more tests or update some of the ones you added?

**Comment by Ricardicus** [comment]
Do you have any tips on how I can check the ctest coverage offline (without using these workflows)?

**Comment by Ricardicus** [comment]
oh snap.. minor formatting.. will fix later today. Seems like test coverage was improved anyway.

**Comment by johnor** [comment]
> Do you have any tips on how I can check the ctest coverage offline (without using these workflows)?

You can see how we run it in CI here: https://github.com/evilcorpltd/n_e_s/blob/f6f6220d8b157161bd150d98a9a5c647bfb97661/.github/workflows/ci-linux.yaml#L108

Build with ENABLE_COVERAGE=ON, install gcovr and run gcovr in the same way

**Review by johnor — APPROVED** [review]

**Pull request merged**
