### PR TITLE
Trigger ci only on push to master or pull requests

### PR DESCRIPTION
**Pull request by johnor**
* Should prevent two runs when someone opens a pull request.

### CODE REVIEW

**Comment by robinlinden** [comment]
Isn't it only running twice because you're pushing your branches to upstream instead of your own repository? :P

**Comment by johnor** [comment]
> Isn't it only running twice because you're pushing your branches to upstream instead of your own repository? :P
> 
> I don't think it's unreasonable that CI runs on all branches in upstream..

Maybe? WIll double check next time I create a PR

**Comment by johnor** [comment]
> > Isn't it only running twice because you're pushing your branches to upstream instead of your own repository? :P
> > I don't think it's unreasonable that CI runs on all branches in upstream..
> 
> Maybe? WIll double check next time I create a PR

You were right, as usual :D

**Comment by robinlinden** [comment]
Haha! :D Just lucky. :D

**Pull request closed without merging**
