### PR TITLE
Add readability-identifier-naming check to clang-tidy

### PR DESCRIPTION
**Pull request by johnor**
What do you think about this check? Some more changes to the style is needed to adapt it completely to our style

### CODE REVIEW

**Comment by robinlinden** [comment]
I think the more we automate checks like this, the better. Ideally human reviewers should only have to think about if a change makes sense. Style and static analysis is better left to the machines. (So basically, this is fantastic!)

**Comment by robinlinden** [comment]
Although, why didn't this catch the issue fixed in #92?

```
  - key:             readability-identifier-naming.MemberCase
    value:           lower_case
```
should catch it, no?

**Comment by johnor** [comment]
Yeah, seems like we need to update our call to run-clang-tidy. I have created #96 to test it.

**Comment by johnor** [comment]
What do we want to do with the following:

Should we change this to an enum instead?
/home/travis/build/evilcorpltd/n_e_s/core/include/core/icpu.h:7:15: error: invalid case style for constant 'C_FLAG' [readability-identifier-naming,-warnings-as-errors]
const uint8_t C_FLAG = 1 << 0; // carry

Constant members: do we want to use the same style as regular members?
/home/travis/build/evilcorpltd/n_e_s/core/src/mos6502.h:22:22: error: invalid case style for constant member 'registers_' [readability-identifier-naming,-warnings-as-errors]
    Registers *const registers_;
                     ^~~~~~~~~~~
                     registers

**Comment by robinlinden** [comment]
Yeah, I'm good with changing the flag constants to being an enum. The current ALL_CAPS name is because I was messing around with them being defines at one point.

As for the constant members, I think they should have the same naming convention as regular members.

**Comment by johnor** [comment]
Passes all tests now. Enums are not handled though and are set to any case. Seems like clang-tidy does not differentiate between enums and enum classes. Changing the cpu flags to an enum class will require some rework and I wont do it in this pull request.

**Pull request merged**
