### PR TITLE
Add executable for running and printing execution log from nestest

### PR DESCRIPTION
**Pull request by johnor**
~~WIP right now. There are separate pull requests for the changes in the nes lib that needs to be merged first. Also need to clean up the string formatting a bit more.~~ Something like https://github.com/fmtlib/fmt would be nice :) The PPU cycle count is also incorrect. 
Part of #143

### CODE REVIEW

**Comment by robinlinden** [comment]
Not a massive fan of checking in a 9000 line log file. I need to think about this one.

**Comment by johnor** [comment]
We don't need to check in the log file and the rom, they are just included while I'm testing. If we want, then we can have a Travis job that downloads the files, runs, and prints the diff.

**Comment by robinlinden** [comment]
Yeah, then I'm good with this. 😄 Looks good! We should probably put them in a separate cmake project as an application instead of letting it live with the unit tests tho.

**Comment by johnor** [comment]
> Yeah, then I'm good with this.  Looks good! We should probably put them in a separate cmake project as an application instead of letting it live with the unit tests tho.

Should I put it in n_e_s_application or create a new one? The program can be used with any rom actually, not only nestest.

**Comment by johnor** [comment]
I think we can start discussing this PR now. The string formatting is not super nice but Im not sure how we can improve it. What do you guys think?

**Comment by robinlinden** [comment]
I think this looks pretty fantastic! Being able to run nestest is great. 😁

Maybe we should create a separate top-level folder for the nestest application? Not sure about having files that you can't build together living in the same src-dir.

**Pull request merged**
